--------------------------------------------------------
--  File created - Thursday-April-18-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CITA
--------------------------------------------------------

  CREATE TABLE "GEOVANNY"."CITA" 
   (	"CODBARFECLIENT" VARCHAR2(50 BYTE), 
	"COD_BABERO" VARCHAR2(20 BYTE), 
	"PARTE" VARCHAR2(20 BYTE), 
	"HORARIO" VARCHAR2(20 BYTE), 
	"COD_CLIENTE" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"FEC_CREACION" VARCHAR2(20 BYTE), 
	"USER_CREACION" VARCHAR2(20 BYTE), 
	"FEC_MOD" VARCHAR2(20 BYTE), 
	"USER_MOD" VARCHAR2(20 BYTE), 
	"FECHA_CITA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "GEOVANNY"."CITA"."CODBARFECLIENT" IS 'LLAVE QUE IDENTIFICA EL BARBERO CLIENTE Y FECHA DE SE REALIZA LA CITA';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."COD_BABERO" IS 'DUI DE BARBERO DE ATENDERA A CLIENTE';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."PARTE" IS 'DIVISION DE LA HORA';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."HORARIO" IS 'HORA QUE SE REALIZANDO LA CITA';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."COD_CLIENTE" IS 'DUI DE CLIENTE  QUE RESERVO CITA';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."ESTADO" IS 'ESTADO DE LA CITA';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."FEC_CREACION" IS 'FECHA DE CREACION DE CITA';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."USER_CREACION" IS 'USUARIO QUE CREO CITA';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."FEC_MOD" IS 'FECHA DE MODIFICACION';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."USER_MOD" IS 'USUARIO QUE MODIFICO';
   COMMENT ON COLUMN "GEOVANNY"."CITA"."FECHA_CITA" IS 'FECHA DE LA CITA';
--------------------------------------------------------
--  DDL for Table ORDEN
--------------------------------------------------------

  CREATE TABLE "GEOVANNY"."ORDEN" 
   (	"CODORDEN" VARCHAR2(20 BYTE), 
	"TOTAL" VARCHAR2(20 BYTE), 
	"CODCLIENTE" VARCHAR2(50 BYTE), 
	"FECHA" VARCHAR2(50 BYTE), 
	"USUARIOCRE" VARCHAR2(20 BYTE), 
	"FECHACRACION" VARCHAR2(20 BYTE), 
	"USUARIOMOD" VARCHAR2(20 BYTE), 
	"FECHAMOD" VARCHAR2(20 BYTE), 
	"CODBARBERO" VARCHAR2(50 BYTE), 
	"COD_BAR_FEC_CLIENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."CODORDEN" IS 'codigo de transaccion';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."TOTAL" IS 'tota de la orden';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."CODCLIENTE" IS 'codigo del cliente';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."FECHA" IS 'fecha de orden';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."USUARIOCRE" IS 'usuario que crea orden';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."FECHACRACION" IS 'fecha de creacion';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."USUARIOMOD" IS 'usuario que modifico';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."FECHAMOD" IS 'fecha de modificacio';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."CODBARBERO" IS 'codigo de barbero';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN"."COD_BAR_FEC_CLIENT" IS 'CODIGO DE LA CITA';
--------------------------------------------------------
--  DDL for Table ORDEN_DETALLE
--------------------------------------------------------

  CREATE TABLE "GEOVANNY"."ORDEN_DETALLE" 
   (	"COD_ORD_PROD" VARCHAR2(20 BYTE), 
	"COD_ORDEN" VARCHAR2(20 BYTE), 
	"COD_PROSER" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"PRECIO" VARCHAR2(20 BYTE), 
	"CANTIDAD" VARCHAR2(20 BYTE), 
	"MONTO" VARCHAR2(20 BYTE), 
	"FECH_CREA" VARCHAR2(20 BYTE), 
	"USER_CREA" VARCHAR2(20 BYTE), 
	"FEC_MOD" VARCHAR2(20 BYTE), 
	"USER_MOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."COD_ORD_PROD" IS 'CODIGO DEL DETALLE DE LA ORDEN';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."COD_ORDEN" IS 'CODIGO DE LA ORDEN DE ESTE DETALLE';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."COD_PROSER" IS 'CODIGO DE PRODUCTO O SERVICIO AGREGADO A ESTE DETALLE';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."DESCRIPCION" IS 'NOMBRE DE; PRODUCTO';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."PRECIO" IS 'PRECIO DEL PRODUCTO';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."CANTIDAD" IS 'NUMERO DE UNIDADES DE PRODUCTOS';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."MONTO" IS 'MONTO DE DINERO DEL VALOR DE LA CANTIDAD DE PRODUCTO';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."FECH_CREA" IS 'FECHA DE CREACION';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."USER_CREA" IS 'USUARIO QUE CREO ESTE DETALLE';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."FEC_MOD" IS 'ULTMA FECHA DE MODIFICACION';
   COMMENT ON COLUMN "GEOVANNY"."ORDEN_DETALLE"."USER_MOD" IS 'USUARIO QUE MODIFICO DATOS';
--------------------------------------------------------
--  DDL for Table PERSONAS
--------------------------------------------------------

  CREATE TABLE "GEOVANNY"."PERSONAS" 
   (	"DUI" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CELULAR" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(250 BYTE), 
	"ROL" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(50 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"FEC_CREACION" VARCHAR2(20 BYTE), 
	"USER_CREACION" VARCHAR2(20 BYTE), 
	"FEC_MOD" VARCHAR2(20 BYTE), 
	"USER_MOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."DUI" IS 'DUI DE LA PERSONA A REGISTRAR';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."NOMBRE" IS 'NOMBRES DE LA PERSONA';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."APELLIDO" IS 'APELLIDOS DE LA PERSONA';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."TELEFONO" IS 'NUMERO TELEFONOFIJO DE LA PERSONA ';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."CELULAR" IS 'NUMEO DE CELULAR DE LA PERSONA';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."DIRECCION" IS 'DIRECCION DE HABITA LA PERSONA';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."ROL" IS 'ROL QUE DESEMPELA DENTRO DEL SISTEMA';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."CORREO" IS 'CORREO PARA CONTACTAR A LA PERSONA';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."ESTADO" IS 'ESTADO DE LA PERSONA DENTRO DEL SISTEMA';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."FEC_CREACION" IS 'FECHA DE CREACION';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."USER_CREACION" IS 'USUARIO QUE INGRESO A LA PERSONA AL SISTEMA';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."FEC_MOD" IS 'FECHA DE MODIFICACION DE DATOS';
   COMMENT ON COLUMN "GEOVANNY"."PERSONAS"."USER_MOD" IS 'USUARIO QUE MODIFICO DATOS DE LA PERSONA AL SISTEMA';
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "GEOVANNY"."PRODUCTOS" 
   (	"COD_PRODUCT" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"PRECIO" NUMBER, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"USERCRE" VARCHAR2(20 BYTE), 
	"FECHCREA" VARCHAR2(20 BYTE), 
	"USERMOD" VARCHAR2(20 BYTE), 
	"FECHMOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "GEOVANNY"."PRODUCTOS"."COD_PRODUCT" IS 'codigo del producto';
   COMMENT ON COLUMN "GEOVANNY"."PRODUCTOS"."DESCRIPCION" IS 'nombre del producto';
   COMMENT ON COLUMN "GEOVANNY"."PRODUCTOS"."PRECIO" IS 'valor del producto';
   COMMENT ON COLUMN "GEOVANNY"."PRODUCTOS"."ESTADO" IS 'estado en sistema del producto';
   COMMENT ON COLUMN "GEOVANNY"."PRODUCTOS"."USERCRE" IS 'usuario que creo producto';
   COMMENT ON COLUMN "GEOVANNY"."PRODUCTOS"."FECHCREA" IS 'fecha de creacion de producto';
   COMMENT ON COLUMN "GEOVANNY"."PRODUCTOS"."USERMOD" IS 'usuario que modifico registro';
   COMMENT ON COLUMN "GEOVANNY"."PRODUCTOS"."FECHMOD" IS 'fecha que se modifico registro';
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "GEOVANNY"."ROLES" 
   (	"COD_ROL" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"FEC_CREACION" VARCHAR2(20 BYTE), 
	"USER_CREACION" VARCHAR2(20 BYTE), 
	"FEC_MOD" VARCHAR2(20 BYTE), 
	"USER_MOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "GEOVANNY"."ROLES"."COD_ROL" IS 'CODIGO DE IDENTIFACION DE ROL';
   COMMENT ON COLUMN "GEOVANNY"."ROLES"."DESCRIPCION" IS 'NOMBRE DEL ROL';
   COMMENT ON COLUMN "GEOVANNY"."ROLES"."ESTADO" IS 'ESTADO DEL ROL ';
   COMMENT ON COLUMN "GEOVANNY"."ROLES"."FEC_CREACION" IS 'FECHA DE CREACION';
   COMMENT ON COLUMN "GEOVANNY"."ROLES"."USER_CREACION" IS 'USUARIO QUE CREO EL ROL';
   COMMENT ON COLUMN "GEOVANNY"."ROLES"."FEC_MOD" IS 'ULTIMA FECHA DE MODIFICACIO';
   COMMENT ON COLUMN "GEOVANNY"."ROLES"."USER_MOD" IS 'USUARO QUE CAMBIO DATOS DEL ROL';
--------------------------------------------------------
--  DDL for Table SERVICIOS
--------------------------------------------------------

  CREATE TABLE "GEOVANNY"."SERVICIOS" 
   (	"CODSERVICIO" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"PRECIO" FLOAT(126), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"USERCRE" VARCHAR2(20 BYTE), 
	"FECHCREA" DATE, 
	"USERMOD" VARCHAR2(20 BYTE), 
	"FECHMOD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "GEOVANNY"."SERVICIOS"."DESCRIPCION" IS 'nombre del servicio';
   COMMENT ON COLUMN "GEOVANNY"."SERVICIOS"."PRECIO" IS 'valor del servicio';
   COMMENT ON COLUMN "GEOVANNY"."SERVICIOS"."ESTADO" IS 'estado en sistema del servicio';
   COMMENT ON COLUMN "GEOVANNY"."SERVICIOS"."USERCRE" IS 'usuario que creo servicio';
   COMMENT ON COLUMN "GEOVANNY"."SERVICIOS"."FECHCREA" IS 'fecha de creacion de ';
   COMMENT ON COLUMN "GEOVANNY"."SERVICIOS"."USERMOD" IS 'usuario que modifico registro';
   COMMENT ON COLUMN "GEOVANNY"."SERVICIOS"."FECHMOD" IS 'fecha que se modifico registro';
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "GEOVANNY"."USUARIOS" 
   (	"DUI" VARCHAR2(20 BYTE), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"PASWWORD" VARCHAR2(20 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"FECHCREA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "GEOVANNY"."USUARIOS"."DUI" IS 'llave de de tabla usuarios';
   COMMENT ON COLUMN "GEOVANNY"."USUARIOS"."USUARIO" IS 'nombre de usuario';
   COMMENT ON COLUMN "GEOVANNY"."USUARIOS"."PASWWORD" IS 'clave de usuario';
   COMMENT ON COLUMN "GEOVANNY"."USUARIOS"."TIPO" IS 'tipo de usuaro en sistema';
   COMMENT ON COLUMN "GEOVANNY"."USUARIOS"."ESTADO" IS 'estado de usuario en sistema';
   COMMENT ON COLUMN "GEOVANNY"."USUARIOS"."FECHCREA" IS 'fecha de creacion';
REM INSERTING into GEOVANNY.CITA
SET DEFINE OFF;
Insert into GEOVANNY.CITA (CODBARFECLIENT,COD_BABERO,PARTE,HORARIO,COD_CLIENTE,ESTADO,FEC_CREACION,USER_CREACION,FEC_MOD,USER_MOD,FECHA_CITA) values ('04018953-501-ENE-201904018953-5','04018953-5','1','09:30','04018953-5','CANCELADO','19-MAR-19','GEOVANNY','24-MAR-19','GEOVANNY','30-MAR-2019');
REM INSERTING into GEOVANNY.ORDEN
SET DEFINE OFF;
Insert into GEOVANNY.ORDEN (CODORDEN,TOTAL,CODCLIENTE,FECHA,USUARIOCRE,FECHACRACION,USUARIOMOD,FECHAMOD,CODBARBERO,COD_BAR_FEC_CLIENT) values ('1','10.00','05189171-3','24-MAR-2019','GEOVANNY','24-MAR-19',null,null,'04288874-5',null);
REM INSERTING into GEOVANNY.ORDEN_DETALLE
SET DEFINE OFF;
REM INSERTING into GEOVANNY.PERSONAS
SET DEFINE OFF;
Insert into GEOVANNY.PERSONAS (DUI,NOMBRE,APELLIDO,TELEFONO,CELULAR,DIRECCION,ROL,CORREO,ESTADO,FEC_CREACION,USER_CREACION,FEC_MOD,USER_MOD) values ('05189171-3','AMAYA FLORES','AMAYA FLORES','2669-3774','78878407','SAN MIGUEL','1','HGAF95@GMAIL.COM','ACTIVO','24-MAR-19','GEOVANNY',null,null);
Insert into GEOVANNY.PERSONAS (DUI,NOMBRE,APELLIDO,TELEFONO,CELULAR,DIRECCION,ROL,CORREO,ESTADO,FEC_CREACION,USER_CREACION,FEC_MOD,USER_MOD) values ('04288874-5','ZARAGOZA','ZARAGOZA','2661-2154','7021-2151','SAN MIGUEL','2','OscarZaragoza85@GMAIL.COM','ACTIVO','24-MAR-19','GEOVANNY',null,null);
Insert into GEOVANNY.PERSONAS (DUI,NOMBRE,APELLIDO,TELEFONO,CELULAR,DIRECCION,ROL,CORREO,ESTADO,FEC_CREACION,USER_CREACION,FEC_MOD,USER_MOD) values ('04018953-5','COREAS CHAVARRIA','COREAS CHAVARRIA','77382166','77382166','SAN MIGUEL','1','DANYCOREAS01@LIVE.COM','ACTIVO','19-MAR-19','GEOVANNY',null,null);
REM INSERTING into GEOVANNY.PRODUCTOS
SET DEFINE OFF;
Insert into GEOVANNY.PRODUCTOS (COD_PRODUCT,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('14','GILLETTE',1,'ACTIVO','EDGAR','21-MAR-19','EDGAR','21-MAR-19');
Insert into GEOVANNY.PRODUCTOS (COD_PRODUCT,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('10','Moco gorila',3.75,'Activo','GEOVANNY','19-MAR-19','GEOVANNY','28-MAR-19');
Insert into GEOVANNY.PRODUCTOS (COD_PRODUCT,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('11','crema humectante',2.25,'inactivo','GEOVANNY','19-MAR-19','GEOVANNY','28-MAR-19');
Insert into GEOVANNY.PRODUCTOS (COD_PRODUCT,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('12','CREMA ANTICASPA',12,'ACTIVO','GEOVANNY','19-MAR-19',null,null);
Insert into GEOVANNY.PRODUCTOS (COD_PRODUCT,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('13','CREMA ANTICASPA 60GR',3.78,'ACTIVO','GEOVANNY','19-MAR-19','GEOVANNY','28-MAR-19');
Insert into GEOVANNY.PRODUCTOS (COD_PRODUCT,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('8','CERA PARA CABELLO XTREME 50GR',3.5,'ANACTIVO','GEOVANNY','18-MAR-19',null,null);
Insert into GEOVANNY.PRODUCTOS (COD_PRODUCT,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('9','VITAMINA E',6.75,'ACTIVO','GEOVANNY','18-MAR-19','GEOVANNY','28-MAR-19');
REM INSERTING into GEOVANNY.ROLES
SET DEFINE OFF;
Insert into GEOVANNY.ROLES (COD_ROL,DESCRIPCION,ESTADO,FEC_CREACION,USER_CREACION,FEC_MOD,USER_MOD) values ('3','CLIENTE','ACTIVO','24-MAR-19','GEOVANNY',null,null);
Insert into GEOVANNY.ROLES (COD_ROL,DESCRIPCION,ESTADO,FEC_CREACION,USER_CREACION,FEC_MOD,USER_MOD) values ('1','ADMINSTRADOR','ACTIVO',null,null,null,null);
Insert into GEOVANNY.ROLES (COD_ROL,DESCRIPCION,ESTADO,FEC_CREACION,USER_CREACION,FEC_MOD,USER_MOD) values ('2','BARBERO','ANACTIVO','18-MAR-19','GEOVANNY',null,null);
REM INSERTING into GEOVANNY.SERVICIOS
SET DEFINE OFF;
Insert into GEOVANNY.SERVICIOS (CODSERVICIO,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('2','CORTE DE BARBA',1.25,'ACTIVO','GEOVANNY',to_date('21-MAR-19','DD-MON-RR'),null,null);
Insert into GEOVANNY.SERVICIOS (CODSERVICIO,DESCRIPCION,PRECIO,ESTADO,USERCRE,FECHCREA,USERMOD,FECHMOD) values ('1','CORTE DE CABELL0',3,'ACTIVO','GEOVANNY',to_date('18-MAR-19','DD-MON-RR'),null,null);
REM INSERTING into GEOVANNY.USUARIOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CITA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEOVANNY"."CITA_PK" ON "GEOVANNY"."CITA" ("CODBARFECLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEOVANNY"."ORDEN_PK" ON "GEOVANNY"."ORDEN" ("CODORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDEN_DETALLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEOVANNY"."ORDEN_DETALLE_PK" ON "GEOVANNY"."ORDEN_DETALLE" ("COD_ORD_PROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEOVANNY"."PERSONAS_PK" ON "GEOVANNY"."PERSONAS" ("DUI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEOVANNY"."PRODUCTOS_PK" ON "GEOVANNY"."PRODUCTOS" ("COD_PRODUCT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEOVANNY"."ROLES_PK" ON "GEOVANNY"."ROLES" ("COD_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEOVANNY"."SERVICIOS_PK" ON "GEOVANNY"."SERVICIOS" ("CODSERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEOVANNY"."USUARIOS_PK" ON "GEOVANNY"."USUARIOS" ("DUI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITA
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("CODBARFECLIENT" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("COD_BABERO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("PARTE" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("HORARIO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("COD_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("FEC_CREACION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("USER_CREACION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."CITA" ADD CONSTRAINT "CITA_PK" PRIMARY KEY ("CODBARFECLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GEOVANNY"."CITA" MODIFY ("FECHA_CITA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDEN
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."ORDEN" MODIFY ("CODORDEN" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN" MODIFY ("CODCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN" MODIFY ("USUARIOCRE" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN" MODIFY ("FECHACRACION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN" MODIFY ("CODBARBERO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN" ADD CONSTRAINT "ORDEN_PK" PRIMARY KEY ("CODORDEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDEN_DETALLE
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("COD_ORD_PROD" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("COD_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("COD_PROSER" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("FECH_CREA" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" MODIFY ("USER_CREA" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" ADD CONSTRAINT "ORDEN_DETALLE_PK" PRIMARY KEY ("COD_ORD_PROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."PERSONAS" MODIFY ("DUI" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PERSONAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PERSONAS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PERSONAS" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PERSONAS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PERSONAS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PERSONAS" MODIFY ("FEC_CREACION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PERSONAS" MODIFY ("USER_CREACION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PERSONAS" ADD CONSTRAINT "PERSONAS_PK" PRIMARY KEY ("DUI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."PRODUCTOS" MODIFY ("COD_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PRODUCTOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PRODUCTOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PRODUCTOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PRODUCTOS" MODIFY ("USERCRE" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."PRODUCTOS" ADD CONSTRAINT "PRODUCTOS_PK" PRIMARY KEY ("COD_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."ROLES" MODIFY ("COD_ROL" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ROLES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ROLES" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("COD_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICIOS
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."SERVICIOS" MODIFY ("CODSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."SERVICIOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."SERVICIOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."SERVICIOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."SERVICIOS" MODIFY ("USERCRE" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."SERVICIOS" MODIFY ("FECHCREA" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."SERVICIOS" ADD CONSTRAINT "SERVICIOS_PK" PRIMARY KEY ("CODSERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."USUARIOS" MODIFY ("DUI" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."USUARIOS" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."USUARIOS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."USUARIOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."USUARIOS" MODIFY ("FECHCREA" NOT NULL ENABLE);
  ALTER TABLE "GEOVANNY"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("DUI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITA
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."CITA" ADD CONSTRAINT "CITA_FK1" FOREIGN KEY ("COD_BABERO")
	  REFERENCES "GEOVANNY"."PERSONAS" ("DUI") ENABLE;
  ALTER TABLE "GEOVANNY"."CITA" ADD CONSTRAINT "CITA_FK2" FOREIGN KEY ("COD_CLIENTE")
	  REFERENCES "GEOVANNY"."PERSONAS" ("DUI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."ORDEN" ADD CONSTRAINT "ORDEN_FK1" FOREIGN KEY ("CODCLIENTE")
	  REFERENCES "GEOVANNY"."PERSONAS" ("DUI") ENABLE;
  ALTER TABLE "GEOVANNY"."ORDEN" ADD CONSTRAINT "ORDEN_FK2" FOREIGN KEY ("CODBARBERO")
	  REFERENCES "GEOVANNY"."PERSONAS" ("DUI") ENABLE;
  ALTER TABLE "GEOVANNY"."ORDEN" ADD CONSTRAINT "ORDEN_FK3" FOREIGN KEY ("COD_BAR_FEC_CLIENT")
	  REFERENCES "GEOVANNY"."CITA" ("CODBARFECLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN_DETALLE
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" ADD CONSTRAINT "ORDEN_DETALLE_FK1" FOREIGN KEY ("COD_ORDEN")
	  REFERENCES "GEOVANNY"."ORDEN" ("CODORDEN") ENABLE;
  ALTER TABLE "GEOVANNY"."ORDEN_DETALLE" ADD CONSTRAINT "ORDEN_DETALLE_FK2" FOREIGN KEY ("COD_PROSER")
	  REFERENCES "GEOVANNY"."PRODUCTOS" ("COD_PRODUCT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "GEOVANNY"."PERSONAS" ADD CONSTRAINT "PERSONAS_FK1" FOREIGN KEY ("ROL")
	  REFERENCES "GEOVANNY"."ROLES" ("COD_ROL") ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDITORIACITASMOD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GEOVANNY"."AUDITORIACITASMOD" 
before UPDATE on CITA for EACH ROW
    declare
    begin 
    
      :new.user_mod :=user;
      :new.fec_mod := sysdate;
    end;
/
ALTER TRIGGER "GEOVANNY"."AUDITORIACITASMOD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDITORIACITASINGRESO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GEOVANNY"."AUDITORIACITASINGRESO" 
before insert on CITA for EACH ROW
    declare
    begin 
    
      :new.user_creacion :=user;
      :new.fec_creacion := sysdate;
    end;
/
ALTER TRIGGER "GEOVANNY"."AUDITORIACITASINGRESO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDITORIAPRODUCTOSMODIF
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GEOVANNY"."AUDITORIAPRODUCTOSMODIF" 
before update on productos for EACH ROW
    declare
    begin 
    
      :new.usermod :=user;
      :new.fechmod := sysdate;
    end;
/
ALTER TRIGGER "GEOVANNY"."AUDITORIAPRODUCTOSMODIF" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VALIDARPRECIOPRODUCTOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GEOVANNY"."VALIDARPRECIOPRODUCTOS" before insert on productos for EACH ROW
    declare
    begin 
      if(:new.precio <0)then 
      :new.precio :=0;
      end if;
    
    end;
/
ALTER TRIGGER "GEOVANNY"."VALIDARPRECIOPRODUCTOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDITORIAPRODUCTOSINGRESO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GEOVANNY"."AUDITORIAPRODUCTOSINGRESO" 
before insert on productos for EACH ROW
    declare
    begin 
    
      :new.usercre :=user;
      :new.fechcrea := sysdate;
    end;
/
ALTER TRIGGER "GEOVANNY"."AUDITORIAPRODUCTOSINGRESO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDITORIAROLMOD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GEOVANNY"."AUDITORIAROLMOD" 
before update on roles for EACH ROW
    declare
    begin 
    
      :new.user_mod :=user;
      :new.fec_mod := sysdate;
    end;
/
ALTER TRIGGER "GEOVANNY"."AUDITORIAROLMOD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDITORIAROLINGRESO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GEOVANNY"."AUDITORIAROLINGRESO" 
before insert on roles for EACH ROW
    declare
    begin 
    
      :new.user_creacion :=user;
      :new.fec_creacion := sysdate;
    end;
/
ALTER TRIGGER "GEOVANNY"."AUDITORIAROLINGRESO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VALIDARPRECIOSERVICIOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GEOVANNY"."VALIDARPRECIOSERVICIOS" before insert on servicios for EACH ROW
    declare
    begin 
      if(:new.precio <0)then 
      :new.precio :=0;
      end if;
    
    end;
/
ALTER TRIGGER "GEOVANNY"."VALIDARPRECIOSERVICIOS" ENABLE;
